### ISSUE TITLE
Crash happened in native code once version upgraded on arm64 linux

### ISSUE THREAD

**Issue by lindeer** [JetBrains/skiko#652]
Not sure if here is the correct report place, but stack trace contained something like `org.jetbrains.skiko.context.ContextHandler.flush()V+12`, different from issue #649 
```
---------------  T H R E A D  ---------------

Current thread (0x000000743c830000):  JavaThread "AWT-EventQueue-0" [_thread_in_native, id=13657, stack(0x00000073b7e00000,0x00000073b8000000)]

Stack: [0x00000073b7e00000,0x00000073b8000000],  sp=0x00000073b7ffa660,  free space=2025k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jetbrains.skia.DirectContextKt.DirectContext_nFlush(J)J+0
j  org.jetbrains.skia.DirectContextKt.access$DirectContext_nFlush(J)J+1
j  org.jetbrains.skia.DirectContext.flush()Lorg/jetbrains/skia/DirectContext;+10
j  org.jetbrains.skiko.context.ContextHandler.flush()V+12
j  org.jetbrains.skiko.context.ContextHandler.draw()V+87
```

Everything went well when my project using `id("org.jetbrains.compose") version "1.2.0-alpha01-dev753"` and `classpath(kotlin("gradle-plugin", version = "1.7.0"))`,  but `gradlew run` crashed once changed as `id("org.jetbrains.compose") version "1.2.0"` and `classpath(kotlin("gradle-plugin", version = "1.7.10"))`. Same issue when I run [template project](https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template) with compose `1.2.2`

here is the log file: [hs_err_pid13628.log](https://github.com/JetBrains/skiko/files/10528867/hs_err_pid13628.log)

```
$ uname -ar
Linux greatwall-pc 5.4.18-80.43.2-generic #GWOEM SMP Wed Mar 9 14:13:16 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by linroid** [comment]
I encountered the same stack

**Comment by dima-avdeev-jb** [comment]
Thanks!

> it's gone after I upgraded the to Compose 1.3.0

Yes, it is fixed in Compose 1.3.0 with Kotlin 1.8.0.

**Comment by lindeer** [comment]
Sorry, but the issue still exists on my amr64 machine  in Compose 1.3.0 with Kotlin 1.8.0 @dima-avdeev-jb 
here is the log:
[hs_err_pid25894.log](https://github.com/JetBrains/skiko/files/10904617/hs_err_pid25894.log)

**Comment by dima-avdeev-jb** [comment]
In your logs I see another one stacktrace:
```
Current thread (0x000000743c830000):  JavaThread "AWT-EventQueue-0" [_thread_in_native, id=13657, stack(0x00000073b7e00000,0x00000073b8000000)]

Stack: [0x00000073b7e00000,0x00000073b8000000],  sp=0x00000073b7ffa660,  free space=2025k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jetbrains.skia.DirectContextKt.DirectContext_nFlush(J)J+0
j  org.jetbrains.skia.DirectContextKt.access$DirectContext_nFlush(J)J+1
j  org.jetbrains.skia.DirectContext.flush()Lorg/jetbrains/skia/DirectContext;+10
j  org.jetbrains.skiko.context.ContextHandler.flush()V+12
j  org.jetbrains.skiko.context.ContextHandler.draw()V+87
j  org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.redrawImmediately()V+231
j  org.jetbrains.skiko.SkiaLayer.paint(Ljava/awt/Graphics;)V+85
```

**Comment by dima-avdeev-jb** [comment]
Does crash happen an application startup?

**Comment by lindeer** [comment]
yes, it does.

**Comment by dima-avdeev-jb** [comment]
Can you please check Compose 1.3.1-rc03 with Kotlin 1.8.10

**Comment by lindeer** [comment]
Still reproduce with Compose 1.3.1-rc03 and Kotlin 1.8.10
here is the new log:
[hs_err_pid12143.log](https://github.com/JetBrains/skiko/files/10918884/hs_err_pid12143.log)

**Comment by lindeer** [comment]
seems my laptop is exceptional, it is acceptable for me to run some local debug tool to collect more info. @dima-avdeev-jb

**Comment by lindeer** [comment]
I believe it is a regression, 'cause it was OK with compose 1.2.0-alpha01-dev753 and kotlin 1.7.0. Do you have any idea of debug steps so that I could have a check locally? I am suspicious of my local java sdk, it is a pre-installed version coming with system.

**Comment by dima-avdeev-jb** [comment]
Can you please try to run this project https://github.com/JetBrains/compose-multiplatform-template
With JDK inside your IntelliJ IDEA. To do so, just click on the green triangle near `fun main()`:


<img width="270" alt="image" src="https://user-images.githubusercontent.com/99798741/224905149-a53088f3-3499-49cf-81a6-cb7e4bbc3256.png">

**Comment by lindeer** [comment]
still not work :sob:

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-652">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
